class CApplication {
   static APPLICATION_NAME              = 'Hidden Skills';

   static APPLICATION_VERSION_FIRST     = 'FIRST'; 

   static APPLICATION_LANGUAGE_ENGLISH  = 'ENGLISH';
   static APPLICATION_LANGUAGE_SPANISH  = 'SPANISH';
   static APPLICATION_LANGUAGE_FRENCH   = 'FRENCH';
   static APPLICATION_LANGUAGE_ITALIAN  = 'ITALIAN';
   static APPLICATION_LANGUAGE_JAPANESE = 'JAPANESE';
   static APPLICATION_LANGUAGE_RUSSIAN  = 'RUSSIAN';
   static APPLICATION_LANGUAGE_CHINESE  = 'CHINESE';
};

export default CApplication;